### ISSUE TITLE
这个到底啥用途呢

### ISSUE THREAD

**Issue by jj89757hhb** [CoderDwang/MoreiTunesConnect_iOS#1]

**Comment by CoderDwang** [comment]
谢谢关注，近期将会进行优化。
主要目的就是实现iTunes connect的查询app状态功能，由于官方的app并不支持多账号登录。目前用的是web访问的方式，近期将会修改为网络请求的方式。

**Comment by CoderDwang** [comment]
@jj89757hhb 现已更新，由于官方的iTunes Connect无法多个账号自由切换，所以做了一个这种东西
